export const LEVEL_PERMISSIONS: Record<number, string[]> = {
  1: ['STAFF', 'VIEW_CASES', 'CREATE_CASE', 'VIEW_TICKETS', 'CLAIM_TICKET', 'CLOSE_TICKET', 'VIEW_LOGS', 'VIEW_ANALYTICS'],
  2: ['STAFF', 'MOD', 'VIEW_CASES', 'CREATE_CASE', 'DELETE_CASE', 'MANAGE_CASES', 'VIEW_TICKETS', 'CLAIM_TICKET', 'CLOSE_TICKET', 'MANAGE_TICKETS', 'VIEW_LOGS', 'EXPORT_LOGS', 'VIEW_ANALYTICS'],
  3: ['STAFF', 'MOD', 'SR_MOD', 'ADMIN', 'VIEW_CASES', 'CREATE_CASE', 'DELETE_CASE', 'MANAGE_CASES', 'VIEW_TICKETS', 'CLAIM_TICKET', 'CLOSE_TICKET', 'MANAGE_TICKETS', 'MANAGE_TICKETS_CONFIG', 'VIEW_LOGS', 'EXPORT_LOGS', 'VIEW_ANALYTICS', 'MANAGE_GUILD', 'MANAGE_STAFF', 'MANAGE_AUTOMOD', 'MANAGE_VERIFICATION'],
  4: ['STAFF', 'MOD', 'SR_MOD', 'ADMIN', 'OWNER', 'VIEW_CASES', 'CREATE_CASE', 'DELETE_CASE', 'MANAGE_CASES', 'VIEW_TICKETS', 'CLAIM_TICKET', 'CLOSE_TICKET', 'MANAGE_TICKETS', 'MANAGE_TICKETS_CONFIG', 'VIEW_LOGS', 'EXPORT_LOGS', 'VIEW_ANALYTICS', 'MANAGE_GUILD', 'MANAGE_STAFF', 'MANAGE_AUTOMOD', 'MANAGE_VERIFICATION', 'VIEW_API_KEYS', 'MANAGE_API_KEYS'],
};

export function hasPermission(userPermissions: string[], required: string): boolean {
  return userPermissions.includes(required) || userPermissions.includes('OWNER');
}

export function getPermissionsForLevel(level: number): string[] {
  return LEVEL_PERMISSIONS[level] || LEVEL_PERMISSIONS[1];
}
